// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvlnjrtcizvtltgsbuvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2bG5qcnRjaXp2dGx0Z3NidXZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTIyOTcsImV4cCI6MjA2MTY4ODI5N30.9t3jPCV3t7gLCRhppJY959KAcdvjrNuQg1x3uj_zkSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);